# Generated by Django 5.1.6 on 2025-03-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_approved_cost_client_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
