# Generated by Django 5.1.6 on 2025-03-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_lead_priority_alter_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='client',
        ),
        migrations.AddField(
            model_name='lead',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('lost', 'Lost'), ('under negotiation', 'Under Negotiation')], default='new', max_length=20),
        ),
    ]
