# Generated by Django 5.1.6 on 2025-03-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_remove_lead_client_lead_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal sent', 'Proposal Sent'), ('lost', 'Lost'), ('under negotiation', 'Under Negotiation')], default='new', max_length=20),
        ),
    ]
