# Generated by Django 5.1.6 on 2025-03-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='custom_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='service',
            field=models.CharField(choices=[('Web', 'Web'), ('App', 'App'), ('Web+App', 'Web + App'), ('Other', 'Other')], default='Web', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal_sent', 'Proposal Sent'), ('lost', 'Lost'), ('under negotiation', 'Under Negotiation')], default='new', max_length=20),
        ),
    ]
