# Generated by Django 5.1.6 on 2025-03-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
